name: Environmental variables

on:
  push:
    branches: [ main ]

    
    
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Run my script
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        

        run: 
          echo "hello, my secret is ${{ secrets.DATABASE_HOST }}"
          echo "connecting to database"

      
