name: Run Script

on:
  push:

env:
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      -name: Run my script
      run: echo "connecting to database"
      
